package com.lyx.dao;

import com.lyx.model.Page;
import com.lyx.model.TGoods;
import com.lyx.model.TGoodsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TGoodsMapper {


	/**
     * 分页查询货物
     * @param page
     * @return
     */
    List<TGoods> findGoodsByStateLimit(Page page);

    /**
     * 分页查询货物根据条件
     * @param page
     * @return
     */
    List<TGoods> findGoodsByGoodsInfoLimit(Page page);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    long countByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int deleteByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int insert(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int insertSelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    List<TGoods> selectByExample(TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    TGoods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") TGoods record, @Param("example") TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int updateByExample(@Param("record") TGoods record, @Param("example") TGoodsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    int updateByPrimaryKey(TGoods record);
}