package com.lyx.dao;

import com.lyx.model.TGoodsTitle;
import com.lyx.model.TGoodsTitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TGoodsTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    long countByExample(TGoodsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int deleteByExample(TGoodsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int insert(TGoodsTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int insertSelective(TGoodsTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    List<TGoodsTitle> selectByExample(TGoodsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    TGoodsTitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") TGoodsTitle record, @Param("example") TGoodsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int updateByExample(@Param("record") TGoodsTitle record, @Param("example") TGoodsTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TGoodsTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_goods_title
     *
     * @mbg.generated Wed Nov 11 20:16:19 GMT+08:00 2020
     */
    int updateByPrimaryKey(TGoodsTitle record);
}