package com.lyx.dao;

import com.lyx.model.Page;
import com.lyx.model.TUser;
import com.lyx.model.TUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TUserMapper {
    /**
     * 分页查询
     * @param page
     * @return
     */
    public List<TUser> findAllUsersLimit(Page page);

    /**
     * 根据条件分页查询
     * @param page
     * @return
     */
    public List<TUser> findUsersByUserLimit(Page page);

    /**
     * 根据页面信息分页查询
     * @param page
     * @return
     */
    public List<TUser> findAllUsersByUserLimit(Page page);

    public TUser findUserByUserNameAndPwd(TUser user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    long countByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int deleteByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int insert(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int insertSelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    List<TUser> selectByExample(TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    TUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int updateByExample(@Param("record") TUser record, @Param("example") TUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user
     *
     * @mbg.generated Mon Nov 09 15:57:06 GMT+08:00 2020
     */
    int updateByPrimaryKey(TUser record);
}