package com.lyx.dao;

import com.lyx.model.TUserTitle;
import com.lyx.model.TUserTitleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface TUserTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    long countByExample(TUserTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int deleteByExample(TUserTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int insert(TUserTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int insertSelective(TUserTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    List<TUserTitle> selectByExample(TUserTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    TUserTitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") TUserTitle record, @Param("example") TUserTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int updateByExample(@Param("record") TUserTitle record, @Param("example") TUserTitleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(TUserTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_title
     *
     * @mbg.generated Fri Nov 13 09:53:16 GMT+08:00 2020
     */
    int updateByPrimaryKey(TUserTitle record);
}