package com.lyx.model;

import java.util.Date;

public class TGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_name
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String goodsName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_source
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String goodsSource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.goods_image
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String goodsImage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.supply
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String supply;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.supply_tel
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String supplyTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.put_time
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private Date putTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.note
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.user_id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.number
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.company
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_goods.state
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.id
     *
     * @return the value of t_goods.id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.id
     *
     * @param id the value for t_goods.id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_name
     *
     * @return the value of t_goods.goods_name
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getGoodsName() {
        return goodsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_name
     *
     * @param goodsName the value for t_goods.goods_name
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName == null ? null : goodsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_source
     *
     * @return the value of t_goods.goods_source
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getGoodsSource() {
        return goodsSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_source
     *
     * @param goodsSource the value for t_goods.goods_source
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setGoodsSource(String goodsSource) {
        this.goodsSource = goodsSource == null ? null : goodsSource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.goods_image
     *
     * @return the value of t_goods.goods_image
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getGoodsImage() {
        return goodsImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.goods_image
     *
     * @param goodsImage the value for t_goods.goods_image
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setGoodsImage(String goodsImage) {
        this.goodsImage = goodsImage == null ? null : goodsImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.supply
     *
     * @return the value of t_goods.supply
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getSupply() {
        return supply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.supply
     *
     * @param supply the value for t_goods.supply
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setSupply(String supply) {
        this.supply = supply == null ? null : supply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.supply_tel
     *
     * @return the value of t_goods.supply_tel
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getSupplyTel() {
        return supplyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.supply_tel
     *
     * @param supplyTel the value for t_goods.supply_tel
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setSupplyTel(String supplyTel) {
        this.supplyTel = supplyTel == null ? null : supplyTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.put_time
     *
     * @return the value of t_goods.put_time
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public Date getPutTime() {
        return putTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.put_time
     *
     * @param putTime the value for t_goods.put_time
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setPutTime(Date putTime) {
        this.putTime = putTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.note
     *
     * @return the value of t_goods.note
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.note
     *
     * @param note the value for t_goods.note
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.user_id
     *
     * @return the value of t_goods.user_id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.user_id
     *
     * @param userId the value for t_goods.user_id
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.number
     *
     * @return the value of t_goods.number
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.number
     *
     * @param number the value for t_goods.number
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.company
     *
     * @return the value of t_goods.company
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.company
     *
     * @param company the value for t_goods.company
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_goods.state
     *
     * @return the value of t_goods.state
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_goods.state
     *
     * @param state the value for t_goods.state
     *
     * @mbg.generated Wed Nov 11 09:31:22 GMT+08:00 2020
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        return "TGoods{" +
                "id=" + id +
                ", goodsName='" + goodsName + '\'' +
                ", goodsSource='" + goodsSource + '\'' +
                ", goodsImage='" + goodsImage + '\'' +
                ", supply='" + supply + '\'' +
                ", supplyTel='" + supplyTel + '\'' +
                ", putTime=" + putTime +
                ", note='" + note + '\'' +
                ", userId=" + userId +
                ", number=" + number +
                ", company='" + company + '\'' +
                ", state=" + state +
                '}';
    }
}